### ISSUE TITLE
switchToFullDatabase() doesn't works 

### ISSUE THREAD

**Issue by kenarab** [qbotics/Rpolyhedra#17]
It returns an environment error

**Comment by kenarab** [comment]
For the moment the working call is 
´Rpolyhedra::switchToFullDatabase()´

It will be solved in v0.2.6

**Comment by leobelen** [comment]
This was solved. Now users can call switchToFullDB to either use the minimal db on the package or use the extended one that is downloaded automatically to the home folder.
