### ISSUE TITLE
package Size

### ISSUE THREAD

**Issue by leobelen** [qbotics/Rpolyhedra#3]
We have like 12mb of txt files for dmccooney source.

And if we scrape all polyedra, RDS file is

Rpolyhedra-dmccooey kenarab$ ls -lh inst/extdata/polyhedra.RDS 

 staff    14M Mar  3 22:36 inst/extdata/polyhedra.RDS

**Comment by kenarab** [comment]
Proposed solution by @leobelen: zip scraped files and unzip them when scraped needed (building and/or testing)

**Comment by kenarab** [comment]
The solution will be have a versioned external repository of .polyhedra object and download it when package is installed

**Comment by kenarab** [comment]
Evaluate using drat instead of our own github repo
