### ISSUE TITLE
Check Licence of Netlib. Make sure is compatible with publication

### ISSUE THREAD

**Issue by leobelen** [qbotics/Rpolyhedra#4]
Is it under the GNU license? I read we only have to republish the use with its own license. As is no commercial there should be no problem.

**Comment by leobelen** [comment]
Sent to the Oak Ridge National Laboratory, since the last reference we have of its owner is Andrew Hume, working there (http://www.netlib.org/master/expanded_liblist.html)

Dear Sir,
I hope today finds you well. I am touching base with you as to ask permission to use the contents of http://www.netlib.org/polyhedra in a new package called Rpolyhedra, which is polyhedra database as R6 objects and 'rgl' visualizing capabilities written in the R language, in order to facilitate its use. It gets the polyhedra from different sources and allows the user to explore and view the polyhedra with ease. The package is hosted in https://github.com/qbotics/Rpolyhedra and in the official R/Cran repositories as “Rpolyhedra”.

The before mentioned package has been released with an MIT license and it is available with source code. In fact, within package will also distribute the polyhedra definition files in  http://www.netlib.org/polyhedra. 

I am directing this mail to you, as netlib lists the package as created by Andrew Hume, working in your institution (http://www.netlib.org/master/expanded_liblist.html).

Instructions on how to use the package are available in https://github.com/qbotics/Rpolyhedra. 

Thanks in advance for your kind work and time,

**Comment by kenarab** [comment]
Any update on this?

**Comment by leobelen** [comment]
Nope, the guy does not seem to be reachable....

Enviado desde mi iPhone

**Comment by kenarab** [comment]
Didn't receive any answer from many trials
