### ISSUE TITLE
Error with numeration of polyhedra while running tests in dmccoey source 

### ISSUE THREAD

**Issue by leobelen** [qbotics/Rpolyhedra#5]
Error: polyhedra.db.saved$getPolyhedron(source = source, polyhedron.name = polyhedron.name) not equal to `current.polyhedron`.
Component “number”: Mean relative difference: 1
Component “state”: Component “number”: Mean relative difference: 1

**Comment by kenarab** [comment]
Solved with  scheduling scraping features.
